-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 10:51:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mlb_stats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mlb_stats
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `mlb_stats` DEFAULT CHARACTER SET utf8 ;
-- USE `mlb_stats` ;

-- -----------------------------------------------------
-- Table `mlb_stats`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `positions` ;

CREATE TABLE IF NOT EXISTS `positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb_stats`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teams` ;

CREATE TABLE IF NOT EXISTS `teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlb_stats`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `players` ;

CREATE TABLE IF NOT EXISTS `players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `position` INT NOT NULL,
  `team` INT NOT NULL,
  `AVG` FLOAT NULL,
  `OBP` FLOAT NULL,
  `OPS` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_players_positions_idx` (`position` ASC),
  INDEX `fk_players_teams1_idx` (`team` ASC),
  CONSTRAINT `fk_players_positions`
    FOREIGN KEY (`position`)
    REFERENCES `positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_teams1`
    FOREIGN KEY (`team`)
    REFERENCES `teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
